# Generated by Django 3.2.9 on 2022-01-14 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=65, verbose_name='amount')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='related data')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Currency name')),
                ('code', models.CharField(blank=True, max_length=6, verbose_name='Currency code')),
                ('sign', models.CharField(max_length=6, verbose_name='Currency sign')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budgetbook.asset')),
                ('bank_name', models.CharField(max_length=255, verbose_name='bank name')),
                ('account_number', models.CharField(max_length=255, unique=True, verbose_name='bank account number')),
            ],
            bases=('budgetbook.asset',),
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budgetbook.asset')),
            ],
            bases=('budgetbook.asset',),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budgetbook.asset')),
                ('card_company_name', models.CharField(max_length=255, verbose_name='card company name')),
                ('monthly_limit', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='card monthly limit amount')),
                ('billing_due_date', models.IntegerField(default=10, verbose_name='due date of monthly billing cycle')),
            ],
            bases=('budgetbook.asset',),
        ),
    ]
