# Generated by Django 3.2.9 on 2022-01-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetbook', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='billing_due_date',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='monthly_limit',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='billing_cycle_date',
            field=models.IntegerField(default=10, verbose_name='date of monthly billing cycle'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The amount of credit you can use to make your purchases', max_digits=65, null=True, verbose_name='credit limit'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='outstanding_balance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Total unpaid amount', max_digits=65, null=True, verbose_name='outstanding balance'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='statement_balance',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The amount you owe on your credit card as of the latest billing cycle. It includes any finance charges and late fees.', max_digits=65, null=True, verbose_name='statement balance'),
        ),
    ]
