# Generated by Django 3.2.9 on 2022-01-15 14:52

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('budgetbook', '0003_auto_20220115_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsDiffBtwStatusAndTextChoiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textchoice_field', models.IntegerField(choices=[(0, 'Expense'), (1, 'Income'), (2, 'Transfer')])),
                ('status_filed', model_utils.fields.StatusField(choices=[('borned_remit', 'borned_remit'), ('borned_payin', 'borned_payin'), ('noticed_remit', 'noticed_remit'), ('noticed_payin', 'noticed_payin'), ('done_remit', 'done_remit'), ('done_payin', 'done_payin')], default='borned_remit', max_length=100, no_check_for_status=True)),
            ],
        ),
    ]
