# Generated by Django 3.2.9 on 2022-01-15 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgetbook', '0004_category_whatsdiffbtwstatusandtextchoicefield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='whatsdiffbtwstatusandtextchoicefield',
            old_name='textchoice_field',
            new_name='int_choice_field',
        ),
        migrations.AddField(
            model_name='category',
            name='classification',
            field=models.IntegerField(choices=[(0, 'Expense'), (1, 'Income'), (2, 'Transfer')], default=0, verbose_name='classification for transaction'),
        ),
        migrations.AddField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created datetime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='category description'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='사용자가 활성화/비활성화를 지정하여 복구할수도 있음', verbose_name='is Active'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='사용자가 삭제하면 사용자는 더이상 접근할 수 없음', verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='category',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified datetime'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='gogo', max_length=128, verbose_name='category name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='parent_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='parent category ID'),
        ),
        migrations.AddField(
            model_name='whatsdiffbtwstatusandtextchoicefield',
            name='txt_choice_filed',
            field=models.CharField(choices=[('EX', 'Expense'), ('IN', 'Income'), ('TR', 'Transfer')], default='EX', max_length=2),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='transaction title')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=65, verbose_name='amount')),
                ('classification', models.IntegerField(choices=[(0, 'Expense'), (1, 'Income'), (2, 'Transfer')], default=0, verbose_name='transaction classification')),
                ('seller', models.CharField(help_text='거래처명. 거래한 업체의 상호명 개인의 이름 등', max_length=127, verbose_name='seller name')),
                ('transaction_datetime', models.DateTimeField(null=True, verbose_name='datetime of transaction')),
                ('data', models.JSONField(help_text='추가적인 세부내역/기재사항 등을 저장', verbose_name='additional transaction data')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='created datetime of this item')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budgetbook.category', verbose_name='transaction category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budgetbook.currency', verbose_name='currency')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budgetbook.asset', verbose_name='payment method')),
            ],
        ),
    ]
