# Generated by Django 3.2.9 on 2022-01-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetbook', '0007_auto_20220116_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='classification',
            field=models.IntegerField(choices=[(0, 'Expense'), (1, 'Income'), (2, 'Transfer')], verbose_name='classification for transaction'),
        ),
    ]
