# Generated by Django 3.2.9 on 2022-01-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetbook', '0008_alter_category_classification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash',
            options={'verbose_name': 'cash', 'verbose_name_plural': 'cashes'},
        ),
        migrations.AlterField(
            model_name='category',
            name='classification',
            field=models.IntegerField(choices=[(0, 'Expense'), (1, 'Income'), (2, 'Transfer')], default=0, verbose_name='classification for transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='data',
            field=models.JSONField(blank=True, help_text='추가적인 세부내역/기재사항 등을 저장', null=True, verbose_name='additional transaction data'),
        ),
    ]
