# Generated by Django 3.2.9 on 2022-01-15 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetbook', '0009_auto_20220116_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(default=85, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budgetbook.currency', verbose_name='currency'),
        ),
    ]
