# Generated by Django 3.2.9 on 2022-01-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetbook', '0010_alter_transaction_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsDiffBtwStatusAndTextChoiceField',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
