# Generated by Django 3.2.9 on 2022-01-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetbook', '0012_auto_20220117_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='billing_cycle_date',
            field=models.IntegerField(default=10, help_text='월마다 돌아오는 대금납부 지정일', verbose_name='date of monthly billing cycle'),
        ),
    ]
