# Generated by Django 3.2.9 on 2022-01-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(default=None, help_text='삭제 상태를 나타냅니다', null=True, verbose_name='User is deleted'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='휴면 상태를 나타냅니다', verbose_name='User is active'),
        ),
    ]
